version: '3'

networks:
  node-networks:
    driver: bridge

services:
  db:
    image: bitnami/mysql:latest
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-networks

  app:
    build:
      context: ./nodeapp
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    command: "npm run start:migrate:prod"
    volumes:
      - ./nodeapp:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - node-networks
    depends_on:
      - db
    ports:
      - "3333:3333"
